version: "3.2"
services:
  mongodb:
    image: mongo
    ports:
      - 27018:27017
    volumes:
      - ./mongodb_data_container:/data/db
  flask-simple:
    build:
      dockerfile: Dockerfile1
      context: .
    ports:
      - "5000:5000"
    command: python auth.py
    volumes:
      - ./src:/usr/src/auth/
